services:
  paper-backend:
    image: ghcr.io/munnotubbel/paper-hand:latest
    restart: always
    environment:
      # App-Konfiguration
      - GIN_MODE=release
      - HTTP_PORT=4242
      - API_SECRET_KEY=${API_SECRET_KEY}
      - ENABLED_PROVIDERS="pubmed,europepmc"
      - PUBMED_BASE_URL=${PUBMED_BASE_URL}
      - PUBMED_API_KEY=${PUBMED_API_KEY}
      - PUBMED_EMAIL=${PUBMED_EMAIL}
      - PUBMED_TOOL=${PUBMED_TOOL}
      - PUBMED_FREE_FULL_TEXT_ONLY=${PUBMED_FREE_FULL_TEXT_ONLY}
      - PUBMED_MAX_PAGES=${PUBMED_MAX_PAGES}
      - PUBMED_SEARCH_TERM=${PUBMED_SEARCH_TERM}
      - CRON_SCHEDULE=${CRON_SCHEDULE}
      - UNPAYWALL_EMAIL=${UNPAYWALL_EMAIL}

      # DB-Verbindung (wird von Docker Compose bereitgestellt)
      - DB_HOST=postgres_meta
      - DB_USER=${POSTGRES_META_USER}
      - DB_PASSWORD=${POSTGRES_META_PASSWORD}
      - DB_NAME=${POSTGRES_META_DB}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - postgres_meta

  postgres_meta:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_META_USER}
      - POSTGRES_PASSWORD=${POSTGRES_META_PASSWORD}
      - POSTGRES_DB=${POSTGRES_META_DB}

  postgres_rated_papers:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db_rated_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_RATED_USER}
      - POSTGRES_PASSWORD=${POSTGRES_RATED_PASSWORD}
      - POSTGRES_DB=${POSTGRES_RATED_DB}
    ports:
      - "5433:5432"

  db-backup:
    image: ghcr.io/munnotubbel/paper-hand-backup:main
    restart: always
    environment:
      - CRON_SCHEDULE="0 3 * * 0" # Sonntag 3 Uhr
      - POSTGRES_HOST=postgres_meta
      - POSTGRES_USER=${POSTGRES_META_USER}
      - POSTGRES_PASSWORD=${POSTGRES_META_PASSWORD}
      - POSTGRES_DB=${POSTGRES_META_DB}
      - BACKUP_S3_BUCKET=${BACKUP_S3_BUCKET}
      - BACKUP_S3_ENDPOINT=${BACKUP_S3_ENDPOINT}
      - BACKUP_S3_ACCESS_KEY=${BACKUP_S3_ACCESS_KEY}
      - BACKUP_S3_SECRET_KEY=${BACKUP_S3_SECRET_KEY}
      - BACKUP_S3_REGION=${BACKUP_S3_REGION}
      - KEEP_BACKUPS=4
      - BACKUP_FILE_PREFIX=meta-db
    depends_on:
      - postgres_meta

  rated-papers-db-backup:
    image: ghcr.io/munnotubbel/paper-hand-backup:main
    restart: always
    environment:
      - CRON_SCHEDULE="0 4 * * 0" # Sonntag 4 Uhr
      - POSTGRES_HOST=postgres_rated_papers
      - POSTGRES_USER=${POSTGRES_RATED_USER}
      - POSTGRES_PASSWORD=${POSTGRES_RATED_PASSWORD}
      - POSTGRES_DB=${POSTGRES_RATED_DB}
      - BACKUP_S3_BUCKET=n8n-backup-postgres-rated-papers
      - BACKUP_S3_ENDPOINT=${BACKUP_S3_ENDPOINT}
      - BACKUP_S3_ACCESS_KEY=${BACKUP_S3_ACCESS_KEY}
      - BACKUP_S3_SECRET_KEY=${BACKUP_S3_SECRET_KEY}
      - BACKUP_S3_REGION=${BACKUP_S3_REGION}
      - KEEP_BACKUPS=4
      - BACKUP_FILE_PREFIX=rated-papers-db
    depends_on:
      - postgres_rated_papers

volumes:
  db_data:
  db_rated_data:
