services:
  paper-backend:
    image: ghcr.io/munnotubbel/paper-hand:main
    restart: always
    environment:
      # App-Konfiguration
      - HTTP_PORT=${HTTP_PORT}
      - ENABLED_PROVIDERS=${ENABLED_PROVIDERS}
      - PUBMED_BASE_URL=${PUBMED_BASE_URL}
      - PUBMED_API_KEY=${PUBMED_API_KEY}
      - PUBMED_EMAIL=${PUBMED_EMAIL}
      - PUBMED_TOOL=${PUBMED_TOOL}
      - PUBMED_FREE_FULL_TEXT_ONLY=${PUBMED_FREE_FULL_TEXT_ONLY}
      - PUBMED_MAX_PAGES=${PUBMED_MAX_PAGES}
      - PUBMED_SEARCH_TERM=${PUBMED_SEARCH_TERM}
      - CRON_SCHEDULE=${CRON_SCHEDULE}
      - UNPAYWALL_EMAIL=${UNPAYWALL_EMAIL}

      # DB-Verbindung (wird von Docker Compose bereitgestellt)
      - DB_HOST=postgres_meta
      - DB_USER=${POSTGRES_META_USER}
      - DB_PASSWORD=${POSTGRES_META_PASSWORD}
      - DB_NAME=${POSTGRES_META_DB}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - postgres_meta

  postgres_meta:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_META_USER}
      - POSTGRES_PASSWORD=${POSTGRES_META_PASSWORD}
      - POSTGRES_DB=${POSTGRES_META_DB}

  db-backup:
    image: ghcr.io/munnotubbel/paper-hand-backup:main
    restart: always
    environment:
      # Cron-Zeitplan (Sonntag um 03:00 Uhr)
      - CRON_SCHEDULE="0 3 * * 0"

      # DB-Verbindungsvariablen
      - POSTGRES_HOST=postgres_meta
      - POSTGRES_USER=${POSTGRES_META_USER}
      - POSTGRES_PASSWORD=${POSTGRES_META_PASSWORD}
      - POSTGRES_DB=${POSTGRES_META_DB}

      # S3-Backup-Bucket-Variablen
      - BACKUP_S3_BUCKET=${BACKUP_S3_BUCKET}
      - BACKUP_S3_ENDPOINT=${BACKUP_S3_ENDPOINT}
      - BACKUP_S3_ACCESS_KEY=${BACKUP_S3_ACCESS_KEY}
      - BACKUP_S3_SECRET_KEY=${BACKUP_S3_SECRET_KEY}
      - BACKUP_S3_REGION=${BACKUP_S3_REGION}
      - KEEP_BACKUPS=4
    entrypoint: >
      sh -c "echo \"$CRON_SCHEDULE /backup-tool >> /var/log/cron.log 2>&1\" > /etc/crontabs/root && crond -f -L /var/log/cron.log"
    depends_on:
      - postgres_meta

volumes:
  db_data:
