version: "3.8"

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  paper-backend:
    image: ghcr.io/munnotubbel/paper-hand:latest
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - db

volumes:
  db_data: {}