name: Docker Publish

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for backend
        id: meta_backend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/Munnotubbel/paper-hand

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta_backend.outputs.tags }}
          labels: ${{ steps.meta_backend.outputs.labels }}

      - name: Extract metadata (tags, labels) for backup tool
        id: meta_backup
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/Munnotubbel/paper-hand-backup

      - name: Build and push backup tool image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backup/Dockerfile
          push: true
          tags: ${{ steps.meta_backup.outputs.tags }}
          labels: ${{ steps.meta_backup.outputs.labels }}